import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}
          <div style={{
            border:"solid 2px #fff",
            margin:"auto",
            width:"90%",
            marginTop:"8px"
          }}>
             <nav
             style={{
              display:"flex",
              justifyContent:"center",
              gap:"40px",
              padding:"5px"
             }}>
                <Link href="/">Home</Link>
                <Link href="/images">images</Link>
                <Link href="/posts">posts</Link>
             </nav>
          </div>
      </body>
    </html>
  );   
} 