import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}
        <div className="parent">
          <div 
          style={{
            display:"flex",
            justifyContent:"space-between",
            background:"gray",
            width:"100%",
            margin:"auto",
            marginTop:"-15px"
          }}>
             <span style={{margin:"7px" , color:"#fff" , fontWeight:"bolder"}}>Your Name</span>
             <nav
             style={{
               margin:"5px 8px 0px 0px",
               display:"flex",
               gap:"20px",
               color:"#fff"
             }}>
                <Link href="/">About</Link>
                <Link href="/projects">Projects</Link>
                <Link href="/contact">Contact</Link>
             </nav>
          </div>
          <h1 style={{
            textAlign:"center",
            position:"relative",
            top:"20px",
            fontSize:"24px",
            fontWeight:"bolder"
          }}>Your Name</h1>
          <p style={{
            textAlign:"center",
            position:"relative",
            top:"20px",
            fontSize:"12px"
          }}>Web Developer</p>
      </div>
      </body>
    </html>
  );   
}